import Head from 'next/head'
import Image from 'next/image'
import Face from '../components/Face'
import { MicrophoneIcon, SearchIcon, ViewGridIcon} from '@heroicons/react/solid'
import Foot from '../components/Foot'
import { useRef } from "react"
import {useRouter} from "next/router"



export default function Home() {
  const router = useRouter();
  const inputRef = useRef(null); 
  const search = (x) => {
    x.preventDefault();
    const term = inputRef.current.value;

    if (!term) return;
    router.push(`/search?term=${term}`)

  };
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Clongle</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className ="flex w-full p-6 justify-between text-gray-600">
        <div className="flex space-x-3 items-center"><p className="link">About</p>
          <p className="link">Store</p></div>
        <div className="flex space-x-3 items-center"><p className="link">Gmail</p>
          <p className="link">Images</p>
          <ViewGridIcon className ="h-20 w-20 p-3 hover:bg-slate-200 cursor-pointer rounded-full" />
        <Face url="https://www.cics.umass.edu/sites/default/files/styles/people_individual/public/headshots/marius_minea.jpg?itok=tefvgUq8"/>
        </div>
      </header>
      <form className =" flex flex-col items-center mt-44 flex-grow w-4/5  ">
        <Image src= "http://pluspng.com/img-png/google-logo-png-google-logo-golge-960.png" height="100" width="300"/>
        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg
        max-w-md rounded-full border px-5 py-3 border-gray-200 items-center sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-6 mr-4 text-gray-600" />
          <input ref ={inputRef} type="text" className="focus:outline-none  flex-grow" />
          <MicrophoneIcon className="h-6"/>
        </div>
        <div className=" flex flex-col w-1/2 space-y-2  justify-center sm:flex-row sm:space-x-4 mt-7 ">
          <button  onClick = {search}className ="butn">Search</button>
          <button onClick = {search} className ="butn">Feeling lucky</button>
        </div>
      </form>
  <Foot></Foot>
    </div>
  )
}
